export const dataBabySize = [
  {
    "id": 01,
    "type": "fruits",
    "name": "Фрукты",
    "weeks": {
      1: null,
      2: {
        "value": "Маковое зерно",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      3: {
        "value": "Маковое зерно",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      4: {
        "value": "Кунжутное семечко",
        "length": 2,
        "weight": 0.1,
        "image": "",
      },
      5: {
        "value": "Рисовое зернышко",
        "length": 6,
        "weight": 0.2,
        "image": "",
      },
      6: {
        "value": "Ягодка черники",
        "length": 1.3,
        "weight": 0.5,
        "image": "",
      },
      7: {
        "value": "Ягодка малины",
        "length": 1.6,
        "weight": 1,
        "image": "",
      },
      8: {
        "value": "Ягода винограда",
        "length": 2.3,
        "weight": 2,
        "image": "",
      },
      9: {
        "value": "Финик",
        "length": 3.1,
        "weight": 4,
        "image": "",
      },
      10: {
        "value": "Инжир",
        "length": 4.1,
        "weight": 7,
        "image": "",
      },
      11: {
        "value": "Слива",
        "length": 5.4,
        "weight": 14,
        "image": "",
      },
      12: {
        "value": "Киви",
        "length": 7.4,
        "weight": 23,
        "image": "",
      },
      13: {
        "value": "Персик",
        "length": 8.7,
        "weight": 43,
        "image": "",
      },
      14: {
        "value": "Груша",
        "length": 10.1,
        "weight": 70,
        "image": "",
      },
      15: {
        "value": "Авокадо",
        "length": 11.6,
        "weight": 100,
        "image": "",
      },
      16: {
        "value": "Апельсин",
        "length": 13,
        "weight": 140,
        "image": "",
      },
      17: {
        "value": "Гранат",
        "length": 14.2,
        "weight": 190,
        "image": "",
      },
      18: {
        "value": "Грейпфрут",
        "length": 15.3,
        "weight": 240,
        "image": "",
      },
      19: {
        "value": "Манго",
        "length": 25.6,
        "weight": 300,
        "image": "",
      },
      20: {
        "value": "Канталупа",
        "length": 26.7,
        "weight": 360,
        "image": "",
      },
      21: {
        "value": "Баклажан",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      22: {
        "value": "Баклажан",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      23: {
        "value": "Баклажан",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      24: {
        "value": "Папайя",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      25: {
        "value": "Папайя",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      26: {
        "value": "Папайя",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      27: {
        "value": "Папайя",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      28: {
        "value": "Тыква",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      29: {
        "value": "Тыква",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      30: {
        "value": "Тыква",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      31: {
        "value": "Тыква",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      32: {
        "value": "Мускатная дыня",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      33: {
        "value": "Мускатная дыня",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      34: {
        "value": "Мускатная дыня",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      35: {
        "value": "Мускатная дыня",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      36: {
        "value": "Арбуз",
        "length": 48-52,
        "weight": 2.8-4,
        "image": "",
      },
      37: {
        "value": "Арбуз",
        "length": 48-52,
        "weight": 2.8-4,
        "image": "",
      },
      38: {
        "value": "Арбуз",
        "length": 48-52,
        "weight": 2.8-4,
        "image": "",
      },
      39: {
        "value": "Арбуз",
        "length": 48-52,
        "weight": 2.8-4,
        "image": "",
      },
    },
  },
  {
    "id": 02,
    "type": "animals",
    "name": "Животные",
    "weeks": {
      1: null,
      2: {
        "value": "Тихоходка",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      3: {
        "value": "Тихоходка",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      4: {
        "value": "Муравей",
        "length": 2,
        "weight": 0.1,
        "image": "",
      },
      5: {
        "value": "Божья коровка",
        "length": 6,
        "weight": 0.2,
        "image": "",
      },
      6: {
        "value": "Пчела",
        "length": 1.3,
        "weight": 0.5,
        "image": "",
      },
      7: {
        "value": "Кокон щелкопряда",
        "length": 1.6,
        "weight": 1,
        "image": "",
      },
      8: {
        "value": "Улитка",
        "length": 2.3,
        "weight": 2,
        "image": "",
      },
      9: {
        "value": "Бабочка",
        "length": 3.1,
        "weight": 4,
        "image": "",
      },
      10: {
        "value": "Стрекоза",
        "length": 4.1,
        "weight": 7,
        "image": "",
      },
      11: {
        "value": "Колибри",
        "length": 5.4,
        "weight": 14,
        "image": "",
      },
      12: {
        "value": "Цыпленок",
        "length": 7.4,
        "weight": 23,
        "image": "",
      },
      13: {
        "value": "Утенок",
        "length": 8.7,
        "weight": 43,
        "image": "",
      },
      14: {
        "value": "Хомячок",
        "length": 10.1,
        "weight": 70,
        "image": "",
      },
      15: {
        "value": "Ципленок пекинской бентамки",
        "length": 11.6,
        "weight": 100,
        "image": "",
      },
      16: {
        "value": "Канарейка",
        "length": 13,
        "weight": 140,
        "image": "",
      },
      17: {
        "value": "Ежонок",
        "length": 14.2,
        "weight": 190,
        "image": "",
      },
      18: {
        "value": "Тупик",
        "length": 15.3,
        "weight": 240,
        "image": "",
      },
      19: {
        "value": "Морская свинка",
        "length": 25.6,
        "weight": 300,
        "image": "",
      },
      20: {
        "value": "Котенок",
        "length": 26.7,
        "weight": 360,
        "image": "",
      },
      21: {
        "value": "Щенок мальтийской болонки",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      22: {
        "value": "Щенок мальтийской болонки",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      23: {
        "value": "Щенок мальтийской болонки",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      24: {
        "value": "Кролик",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      25: {
        "value": "Кролик",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      26: {
        "value": "Кролик",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      27: {
        "value": "Кролик",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      28: {
        "value": "Щенок",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      29: {
        "value": "Щенок",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      30: {
        "value": "Щенок",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      31: {
        "value": "Щенок",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      32: {
        "value": "Львенок",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      33: {
        "value": "Львенок",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      34: {
        "value": "Львенок",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      35: {
        "value": "Львенок",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      36: {
        "value": "Ягненок",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      37: {
        "value": "Ягненок",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      38: {
        "value": "Ягненок",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      39: {
        "value": "Ягненок",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
    },
  },
  {
    "id": 03,
    "type": "sweets",
    "name": "Сладости",
    "weeks": {
      1: null,
      2: {
        "value": "Крупинка сахара",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      3: {
        "value": "Крупинка сахара",
        "length": 1,
        "weight": 0,
        "image": "",
      },
      4: {
        "value": "Кондитерская посыпка",
        "length": 2,
        "weight": 0.1,
        "image": "",
      },
      5: {
        "value": "Драже 'Смарти",
        "length": 6,
        "weight": 0.2,
        "image": "",
      },
      6: {
        "value": "Мармеладное драже",
        "length": 1.3,
        "weight": 0.5,
        "image": "",
      },
      7: {
        "value": "Мармеладный мишка",
        "length": 1.6,
        "weight": 1,
        "image": "",
      },
      8: {
        "value": "Мармеладная кола",
        "length": 2.3,
        "weight": 2,
        "image": "",
      },
      9: {
        "value": "Конфета",
        "length": 3.1,
        "weight": 4,
        "image": "",
      },
      10: {
        "value": "Печенье с предсказанием",
        "length": 4.1,
        "weight": 7,
        "image": "",
      },
      11: {
        "value": "Макарун",
        "length": 5.4,
        "weight": 14,
        "image": "",
      },
      12: {
        "value": "Капкейк",
        "length": 7.4,
        "weight": 23,
        "image": "",
      },
      13: {
        "value": "Брауни",
        "length": 8.7,
        "weight": 43,
        "image": "",
      },
      14: {
        "value": "Лунное печенье",
        "length": 10.1,
        "weight": 70,
        "image": "",
      },
      15: {
        "value": "Пончик",
        "length": 11.6,
        "weight": 100,
        "image": "",
      },
      16: {
        "value": "Бельгийская вафля",
        "length": 13,
        "weight": 140,
        "image": "",
      },
      17: {
        "value": "Кусочек торта",
        "length": 14.2,
        "weight": 190,
        "image": "",
      },
      18: {
        "value": "Мороженое рожок",
        "length": 15.3,
        "weight": 240,
        "image": "",
      },
      19: {
        "value": "Оладушек",
        "length": 25.6,
        "weight": 300,
        "image": "",
      },
      20: {
        "value": "Большая порция попкорна",
        "length": 26.7,
        "weight": 360,
        "image": "",
      },
      21: {
        "value": "Фруктовый пирог",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      22: {
        "value": "Фруктовый пирог",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      23: {
        "value": "Фруктовый пирог",
        "length": 28-30,
        "weight": 430-600,
        "image": "",
      },
      24: {
        "value": "Шоколадный торт",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      25: {
        "value": "Шоколадный торт",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      26: {
        "value": "Шоколадный торт",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      27: {
        "value": "Шоколадный торт",
        "length": 34-37,
        "weight": 660-1000,
        "image": "",
      },
      28: {
        "value": "Коробка конфет",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      29: {
        "value": "Коробка конфет",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      30: {
        "value": "Коробка конфет",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      31: {
        "value": "Коробка конфет",
        "length": 38-42,
        "weight": 1150-1700,
        "image": "",
      },
      32: {
        "value": "Сахарная вата",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      33: {
        "value": "Сахарная вата",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      34: {
        "value": "Сахарная вата",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      35: {
        "value": "Сахарная вата",
        "length": 43-47,
        "weight": 1900-2600,
        "image": "",
      },
      36: {
        "value": "Свадебный торт",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      37: {
        "value": "Свадебный торт",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      38: {
        "value": "Свадебный торт",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
      39: {
        "value": "Свадебный торт",
        "length": 48-52,
        "weight": 2800-4000,
        "image": "",
      },
    },
  }
];
